### ISSUE TITLE
how to choose the means and stds in data.py

### ISSUE THREAD

**Issue by GuokaiLiu** [samet-akcay/ganomaly#20]
Hello, Samet
I have two questions to consult for your help.
- Why choose the following means and stds In `data.py`:
```
# for cifar10
transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))

# for minist
transforms.Normalize((0.1307,), (0.3081,))
```
- For my own dataset, how to choose or calculate the mean and std?

Thank you very much!

**Comment by samet-akcay** [comment]
Hi GuokaiLiu, 
Sorry for my late reply.  Those numbers come with PyTorch data loader. Cifar10 has 3 mean and std values, while MNIST only has one. This is mainly because CIFAR images are 3-channel and MNIST images are 1-channel images.

If you want to calculate the mean and standard deviation for your own dataset, you could iterate through your entire images, and find the mean values of each channel. Similarwise, follow the same step for standard deviation as well. In practice, however, I've seen many people who simply use ImageNet mean and standard deviation for their custom datasets.

**Comment by samet-akcay** [comment]
Due to inactivity, I assume that this has been resolved, and am closing the issue. Feel free to re-open it if you still encounter any further problems.
