### ISSUE TITLE
not Semi-Supervised

### ISSUE THREAD

**Issue by newlei** [samet-akcay/ganomaly#24]
As you mentioned in your paper, this is a Semi-Supervised Anomaly Detection. However,  I can't agree with this point. In the training process, the input is normal data without unlabeled data. Specifically, instead of part, all input data label is marked as normal. From this perspective, the model is not a semi-supervised model.  Can you explain the semi-supervision?

**Comment by samet-akcay** [comment]
Well, from a training perspective, you are right. We only use normal labels during training and have not used the label information, which makes it unsupervised. After some discussion, we were asked to change the name to semi-supervised model due to the Integrated-test evaluation, meaning that the test set is checked after every epoch, which takes labels into account.

**Comment by lanlanwei** [comment]
Hello,I am reading your paper now.Thank you for your answer about this quetion.Do you think of  using the label information in the future?
