### ISSUE TITLE
Is Discriminator loss correct??

### ISSUE THREAD

**Issue by toshikwa** [samet-akcay/ganomaly#28]
Hi, I'm trying to understand the mechanism of GANomaly.

I read model.py and I thought Discriminator Loss was incorrect because it should maximize Ladv or minimize BCE.

Is Discriminator loss correct??

**Comment by lcd111** [comment]
Hi, I think the I discriminator is right about loss and its purpose is to close the distance between real and fake。But I think there's a problem with the generator loss where the first term is redundant

**Comment by JiangAndy** [comment]
@samet-akcay I also get confused, 
first, in your paper, you use the Ladv loss in the generator part, but in your code, you use the BCE loss; 

second, you use the Ladv loss in the discriminator part, but I think you should maximize it rather than minimize it, 

third, in your test code, you use the L2 loss rather than the L1 loss in you paper. 

so which is the right?

**Comment by GerardMaggiolino** [comment]
I have the same issues. As there's some ambiguity in subscripts, I'll clarify what I'm referring to here: 
- L_adv := L2 loss between latent vectors of the discriminator for generated and real image. 
- L_con := L1 loss between real and generated images. 
- L_enc := L2 loss between latent vectors of the double encoder system. 
- L_bce := Standard log loss for GAN, minimized for auto-encoder, maximized for discriminator. 
 
The paper suggests that L = L_adv + L_con + L_enc is minimized through the entire network. It does not provide a discriminator specific loss - it seems reasonable to assume L is minimized by the encoder-decoder-encoder module, while the discriminator maximizes L_bce. 

However, in the code, we see L = L_bce + L_con + L_enc. This seems like a solid change for the encoder-decoder-encoder module, where L_bce substitutes the feature map loss. 

**The largest issue** is the discriminator loss. Here, we see in the code that it minimizes L_adv. This is intuitively nonsensical,  as minimizing distance between feature maps will prevent the discriminator from distinguishing between real and generated images. Furthermore, the discriminator is never optimized to explicitly distinguish between real and generated images with L_bce, thus not providing a meaningful signal to L of the encoder-decoder-encoder module. 

**In preliminary experiments**, it appears that the discriminator module can be entirely removed with no affect on AUC. I'll look into it more, and follow up with the author if this is truly the case.

**Comment by lcd111** [comment]
@GerardMaggiolino    Hi,What I understand is that the discriminator can be removed completely, because the most important part of the network is the generator. The discriminator is only used to assist, and the reason why he uses the discriminator here is that he uses the GAN and it's a bit wasteful not to use discriminators.  If you remove the discriminator, then the network is actually coding, decoding and coding. Loss= L_adv+L_con.   It's nothing to do with gan.

**Comment by samet-akcay** [comment]
Hey everyone, I'll try to make things clearer.

As @GerardMaggiolino points out, the objective of the generator is `L = L_adv + L_con + L_enc`, and the objective of the discriminator is the vanilla discriminator loss. As all you raised, the previous version of the code, which was the wrong upload, was a bit different than what was described in the paper. 

The reason why we preferred feature matching loss is for a consistent comparison against the previous approaches [39, 40] claiming that feature matching loss outperforms bce. However, we empirically didn't observe much difference. For the sake of consistency, I've updated the repo with the correct loss as described in the paper.

For the discriminator training, I've updated the repo to adversarially train the discriminator. - again, this was just the wrong upload but doesn't impact the training of mnist and cifar. As @GerardMaggiolino and @lcd111 mentioned, there is almost no difference between training with and without the discriminator (avg auc on cifar: 0.759 vs 0.755) for toy datasets such as MNIST and CIFAR10. This is mainly because the generator network is powerful enough for toy datasets to successfully reconstruct the input without the need for an additional discriminator network. However, this is not the case for more challenging tasks. We empirically observe that the discriminator network does improve the performance when trained on datasets with larger image sizes, where the reconstruction of the input is rather challenging. Utilizing the discriminator within the pipeline, therefore, improves the overall performance for more difficult tasks.

I've just started to work on the journal extension of the paper, where the pipeline will be thoroughly explained with a broader experimental setup.

Let me know if you have any questions.

**Comment by GerardMaggiolino** [comment]
Thank you for the response @samet-akcay! In the prior code, feature map distance was minimized for the discriminator rather than the generator module. I have a few more questions if you have the time. 

What data sets have you been noticing increased performance on? Do you continue to use a weight of 50 for contextual loss? Both contextual and feature mapping losses are geared towards image reconstruction, but contextual loss weighted much higher.

**Comment by zwzhang123** [comment]
@GerardMaggiolino 
in L = L_adv + L_con + L_enc, authors set the weight of L_con=50, is that means reconstruction error plays an important role in loss funtion? how about remove anthor two loss?

**Comment by zwzhang123** [comment]
@samet-akcay 
why use the L_adv loss of discriminator feature map, not the generator's?
