### ISSUE TITLE
I met this error. When train time/

### ISSUE THREAD

**Issue by bemoregt** [samet-akcay/ganomaly#3]
Hi, @samet-akcay 

I met this error.

  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 169, in add_module
    raise KeyError("module name can't contain \".\"")
KeyError: 'module name can\'t contain "."'

What's wrong with me?

Thanks in advance.

from @bemoregt.

**Comment by samet-akcay** [comment]
Hi @bemoregt, you most probably use PyTorch v0.4, which does not support "." within module names. As stated in README.md, PyTorch v0.4 is not supported at the minute. We'll be releasing a branch supporting the latest version of PyTorch.

In order to fix this, you need to use PyTorch v0.3.

Let me know if you have any other questions.

Cheers,
Samet

**Comment by bemoregt** [comment]
Thanks a lot.

It's helpful~

from @bemoregt.
